// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package io.zero._03_netty.example.im.pb;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 性别枚举
   * </pre>
   *
   * Protobuf enum {@code Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BOY = 0;</code>
     */
    BOY(0),
    /**
     * <code>Girl = 1;</code>
     */
    Girl(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BOY = 0;</code>
     */
    public static final int BOY_VALUE = 0;
    /**
     * <code>Girl = 1;</code>
     */
    public static final int Girl_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return BOY;
        case 1: return Girl;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.zero._03_netty.example.im.pb.Protocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Gender)
  }

  public interface SendMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SendMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <code>.Gender gender = 3;</code>
     * @return The gender.
     */
    io.zero._03_netty.example.im.pb.Protocol.Gender getGender();

    /**
     * <code>uint64 sendTime = 4;</code>
     * @return The sendTime.
     */
    long getSendTime();

    /**
     * <code>bytes payload = 5;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * 用于发送给服务端的消息
   * </pre>
   *
   * Protobuf type {@code SendMessage}
   */
  public static final class SendMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SendMessage)
      SendMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendMessage.newBuilder() to construct.
    private SendMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMessage() {
      name_ = "";
      gender_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.zero._03_netty.example.im.pb.Protocol.internal_static_SendMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.zero._03_netty.example.im.pb.Protocol.internal_static_SendMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.zero._03_netty.example.im.pb.Protocol.SendMessage.class, io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 3;
    private int gender_ = 0;
    /**
     * <code>.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.Gender gender = 3;</code>
     * @return The gender.
     */
    @java.lang.Override public io.zero._03_netty.example.im.pb.Protocol.Gender getGender() {
      io.zero._03_netty.example.im.pb.Protocol.Gender result = io.zero._03_netty.example.im.pb.Protocol.Gender.forNumber(gender_);
      return result == null ? io.zero._03_netty.example.im.pb.Protocol.Gender.UNRECOGNIZED : result;
    }

    public static final int SENDTIME_FIELD_NUMBER = 4;
    private long sendTime_ = 0L;
    /**
     * <code>uint64 sendTime = 4;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 5;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (gender_ != io.zero._03_netty.example.im.pb.Protocol.Gender.BOY.getNumber()) {
        output.writeEnum(3, gender_);
      }
      if (sendTime_ != 0L) {
        output.writeUInt64(4, sendTime_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(5, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (gender_ != io.zero._03_netty.example.im.pb.Protocol.Gender.BOY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sendTime_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.zero._03_netty.example.im.pb.Protocol.SendMessage)) {
        return super.equals(obj);
      }
      io.zero._03_netty.example.im.pb.Protocol.SendMessage other = (io.zero._03_netty.example.im.pb.Protocol.SendMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (gender_ != other.gender_) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.zero._03_netty.example.im.pb.Protocol.SendMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用于发送给服务端的消息
     * </pre>
     *
     * Protobuf type {@code SendMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SendMessage)
        io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.zero._03_netty.example.im.pb.Protocol.internal_static_SendMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.zero._03_netty.example.im.pb.Protocol.internal_static_SendMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.zero._03_netty.example.im.pb.Protocol.SendMessage.class, io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder.class);
      }

      // Construct using io.zero._03_netty.example.tcp_protobuf.pb.Protocol.SendMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        name_ = "";
        gender_ = 0;
        sendTime_ = 0L;
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.zero._03_netty.example.im.pb.Protocol.internal_static_SendMessage_descriptor;
      }

      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.SendMessage getDefaultInstanceForType() {
        return io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.SendMessage build() {
        io.zero._03_netty.example.im.pb.Protocol.SendMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.SendMessage buildPartial() {
        io.zero._03_netty.example.im.pb.Protocol.SendMessage result = new io.zero._03_netty.example.im.pb.Protocol.SendMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.zero._03_netty.example.im.pb.Protocol.SendMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sendTime_ = sendTime_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.zero._03_netty.example.im.pb.Protocol.SendMessage) {
          return mergeFrom((io.zero._03_netty.example.im.pb.Protocol.SendMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.zero._03_netty.example.im.pb.Protocol.SendMessage other) {
        if (other == io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                gender_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                sendTime_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.Gender gender = 3;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @return The gender.
       */
      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.Gender getGender() {
        io.zero._03_netty.example.im.pb.Protocol.Gender result = io.zero._03_netty.example.im.pb.Protocol.Gender.forNumber(gender_);
        return result == null ? io.zero._03_netty.example.im.pb.Protocol.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(io.zero._03_netty.example.im.pb.Protocol.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <code>uint64 sendTime = 4;</code>
       * @return The sendTime.
       */
      @java.lang.Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>uint64 sendTime = 4;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sendTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 5;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 5;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SendMessage)
    }

    // @@protoc_insertion_point(class_scope:SendMessage)
    private static final io.zero._03_netty.example.im.pb.Protocol.SendMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.zero._03_netty.example.im.pb.Protocol.SendMessage();
    }

    public static io.zero._03_netty.example.im.pb.Protocol.SendMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMessage>
        PARSER = new com.google.protobuf.AbstractParser<SendMessage>() {
      @java.lang.Override
      public SendMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SendMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.zero._03_netty.example.im.pb.Protocol.SendMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReplyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReplyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>uint64 replyTime = 2;</code>
     * @return The replyTime.
     */
    long getReplyTime();

    /**
     * <code>.SendMessage sender = 3;</code>
     * @return Whether the sender field is set.
     */
    boolean hasSender();
    /**
     * <code>.SendMessage sender = 3;</code>
     * @return The sender.
     */
    io.zero._03_netty.example.im.pb.Protocol.SendMessage getSender();
    /**
     * <code>.SendMessage sender = 3;</code>
     */
    io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder getSenderOrBuilder();
  }
  /**
   * <pre>
   * 用于回复客户端的消息
   * </pre>
   *
   * Protobuf type {@code ReplyMessage}
   */
  public static final class ReplyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReplyMessage)
      ReplyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReplyMessage.newBuilder() to construct.
    private ReplyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReplyMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReplyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.zero._03_netty.example.im.pb.Protocol.internal_static_ReplyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.zero._03_netty.example.im.pb.Protocol.internal_static_ReplyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.zero._03_netty.example.im.pb.Protocol.ReplyMessage.class, io.zero._03_netty.example.im.pb.Protocol.ReplyMessage.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int REPLYTIME_FIELD_NUMBER = 2;
    private long replyTime_ = 0L;
    /**
     * <code>uint64 replyTime = 2;</code>
     * @return The replyTime.
     */
    @java.lang.Override
    public long getReplyTime() {
      return replyTime_;
    }

    public static final int SENDER_FIELD_NUMBER = 3;
    private io.zero._03_netty.example.im.pb.Protocol.SendMessage sender_;
    /**
     * <code>.SendMessage sender = 3;</code>
     * @return Whether the sender field is set.
     */
    @java.lang.Override
    public boolean hasSender() {
      return sender_ != null;
    }
    /**
     * <code>.SendMessage sender = 3;</code>
     * @return The sender.
     */
    @java.lang.Override
    public io.zero._03_netty.example.im.pb.Protocol.SendMessage getSender() {
      return sender_ == null ? io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance() : sender_;
    }
    /**
     * <code>.SendMessage sender = 3;</code>
     */
    @java.lang.Override
    public io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder getSenderOrBuilder() {
      return sender_ == null ? io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance() : sender_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (replyTime_ != 0L) {
        output.writeUInt64(2, replyTime_);
      }
      if (sender_ != null) {
        output.writeMessage(3, getSender());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (replyTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, replyTime_);
      }
      if (sender_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSender());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.zero._03_netty.example.im.pb.Protocol.ReplyMessage)) {
        return super.equals(obj);
      }
      io.zero._03_netty.example.im.pb.Protocol.ReplyMessage other = (io.zero._03_netty.example.im.pb.Protocol.ReplyMessage) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (getReplyTime()
          != other.getReplyTime()) return false;
      if (hasSender() != other.hasSender()) return false;
      if (hasSender()) {
        if (!getSender()
            .equals(other.getSender())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + REPLYTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReplyTime());
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.zero._03_netty.example.im.pb.Protocol.ReplyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用于回复客户端的消息
     * </pre>
     *
     * Protobuf type {@code ReplyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReplyMessage)
        io.zero._03_netty.example.im.pb.Protocol.ReplyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.zero._03_netty.example.im.pb.Protocol.internal_static_ReplyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.zero._03_netty.example.im.pb.Protocol.internal_static_ReplyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.zero._03_netty.example.im.pb.Protocol.ReplyMessage.class, io.zero._03_netty.example.im.pb.Protocol.ReplyMessage.Builder.class);
      }

      // Construct using io.zero._03_netty.example.tcp_protobuf.pb.Protocol.ReplyMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        replyTime_ = 0L;
        sender_ = null;
        if (senderBuilder_ != null) {
          senderBuilder_.dispose();
          senderBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.zero._03_netty.example.im.pb.Protocol.internal_static_ReplyMessage_descriptor;
      }

      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.ReplyMessage getDefaultInstanceForType() {
        return io.zero._03_netty.example.im.pb.Protocol.ReplyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.ReplyMessage build() {
        io.zero._03_netty.example.im.pb.Protocol.ReplyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.zero._03_netty.example.im.pb.Protocol.ReplyMessage buildPartial() {
        io.zero._03_netty.example.im.pb.Protocol.ReplyMessage result = new io.zero._03_netty.example.im.pb.Protocol.ReplyMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.zero._03_netty.example.im.pb.Protocol.ReplyMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.replyTime_ = replyTime_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sender_ = senderBuilder_ == null
              ? sender_
              : senderBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.zero._03_netty.example.im.pb.Protocol.ReplyMessage) {
          return mergeFrom((io.zero._03_netty.example.im.pb.Protocol.ReplyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.zero._03_netty.example.im.pb.Protocol.ReplyMessage other) {
        if (other == io.zero._03_netty.example.im.pb.Protocol.ReplyMessage.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getReplyTime() != 0L) {
          setReplyTime(other.getReplyTime());
        }
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                replyTime_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getSenderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private long replyTime_ ;
      /**
       * <code>uint64 replyTime = 2;</code>
       * @return The replyTime.
       */
      @java.lang.Override
      public long getReplyTime() {
        return replyTime_;
      }
      /**
       * <code>uint64 replyTime = 2;</code>
       * @param value The replyTime to set.
       * @return This builder for chaining.
       */
      public Builder setReplyTime(long value) {
        
        replyTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 replyTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        replyTime_ = 0L;
        onChanged();
        return this;
      }

      private io.zero._03_netty.example.im.pb.Protocol.SendMessage sender_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.zero._03_netty.example.im.pb.Protocol.SendMessage, io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder, io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder> senderBuilder_;
      /**
       * <code>.SendMessage sender = 3;</code>
       * @return Whether the sender field is set.
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       * @return The sender.
       */
      public io.zero._03_netty.example.im.pb.Protocol.SendMessage getSender() {
        if (senderBuilder_ == null) {
          return sender_ == null ? io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance() : sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      public Builder setSender(io.zero._03_netty.example.im.pb.Protocol.SendMessage value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      public Builder setSender(
          io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      public Builder mergeSender(io.zero._03_netty.example.im.pb.Protocol.SendMessage value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            sender_ != null &&
            sender_ != io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance()) {
            getSenderBuilder().mergeFrom(value);
          } else {
            sender_ = value;
          }
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sender_ = null;
        if (senderBuilder_ != null) {
          senderBuilder_.dispose();
          senderBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      public io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder getSenderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      public io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_ == null ?
              io.zero._03_netty.example.im.pb.Protocol.SendMessage.getDefaultInstance() : sender_;
        }
      }
      /**
       * <code>.SendMessage sender = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.zero._03_netty.example.im.pb.Protocol.SendMessage, io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder, io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder>
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.zero._03_netty.example.im.pb.Protocol.SendMessage, io.zero._03_netty.example.im.pb.Protocol.SendMessage.Builder, io.zero._03_netty.example.im.pb.Protocol.SendMessageOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReplyMessage)
    }

    // @@protoc_insertion_point(class_scope:ReplyMessage)
    private static final io.zero._03_netty.example.im.pb.Protocol.ReplyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.zero._03_netty.example.im.pb.Protocol.ReplyMessage();
    }

    public static io.zero._03_netty.example.im.pb.Protocol.ReplyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReplyMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReplyMessage>() {
      @java.lang.Override
      public ReplyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReplyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReplyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.zero._03_netty.example.im.pb.Protocol.ReplyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReplyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReplyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\"c\n\013SendMessage\022\n\n\002id\030\001 " +
      "\001(\003\022\014\n\004name\030\002 \001(\t\022\027\n\006gender\030\003 \001(\0162\007.Gend" +
      "er\022\020\n\010sendTime\030\004 \001(\004\022\017\n\007payload\030\005 \001(\014\"P\n" +
      "\014ReplyMessage\022\017\n\007success\030\001 \001(\010\022\021\n\treplyT" +
      "ime\030\002 \001(\004\022\034\n\006sender\030\003 \001(\0132\014.SendMessage*" +
      "\033\n\006Gender\022\007\n\003BOY\020\000\022\010\n\004Girl\020\001B5\n)io.zero." +
      "_03_netty.example.tcp_protobuf.pbB\010Proto" +
      "colb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SendMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "SendTime", "Payload", });
    internal_static_ReplyMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReplyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReplyMessage_descriptor,
        new java.lang.String[] { "Success", "ReplyTime", "Sender", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
